### ISSUE TITLE
Food Items Backend

### ISSUE THREAD

**Issue by smithjilks** [0x6f736f646f/uber4freefood#10]
A db with the following fields:

- foodId
- foodName
- dietType
- description
- specialIngredients
- serving
- specialNote
- foodImageId
- locationLat
- locationLong
- status:
- createdAt
- deletedAt
- updatedAt

The backend should allow for manipulation of the status field.

**Comment by smithjilks** [comment]
and the updatedAT field as well

**Comment by SammyOina** [comment]
working on it

**Comment by SammyOina** [comment]
I have built the API using Gin with most of the requested fields, currently writing a readme and a possible docker deployment 
missing fields are: created at
deleted at
updated at

**Comment by SammyOina** [comment]
Done

**Comment by SammyOina** [comment]
just merge the pull request and the issue will be closed

**Comment by smithjilks** [comment]
I forgot two important fields
angelUserID
humanUserID

**Comment by SammyOina** [comment]
I'll add the fields today

**Comment by smithjilks** [comment]
when you updated the fields, did you add patch to humanUserID and updatedAT

**Comment by smithjilks** [comment]
Also add status and message to the response upon patching

**Comment by SammyOina** [comment]
do you want to be able to patch all the fields

**Comment by SammyOina** [comment]
working on status and message then

**Comment by SammyOina** [comment]
I have enabled patch for all fields
