### ISSUE TITLE
Collapsing Food Api and User Api into one Api with routes remaining

### ISSUE THREAD

**Issue by SammyOina** [0x6f736f646f/uber4freefood#14]
I think it would be simpler to bring two APIs into one

**Comment by rodneyosodo** [comment]
Why would it be easier?

**Comment by SammyOina** [comment]
just for uniformity I don't know if it will be negative on performance though

**Comment by rodneyosodo** [comment]
Yes it would introduce an overhead but it would be easier to manage

**Comment by SammyOina** [comment]
ok then let them be separate then
